### ISSUE TITLE
Relicense DPsim

### ISSUE THREAD

**Issue by m-mirz** [dpsim-simulator/dpsim#6]
DPsim started as a GPL3 project, partly due to its dependency on VILLASnode, which is licensed under the GPL3 as well. Since the GPL3 is a strong barrier for many potential contributors, I would like to relicense the whole project under the MPL2 license.

The MPL2 is not as viral as the GPL3 and also Eigen3, one of the core libraries used in DPsim is licensed under the MPL2. Of course, I would move the code associated to VILLASnode to an external repository.

**Comment by DanielDoehring** [comment]
I approve this motion to relicense DPsim under the MPL2.

**Comment by junjie-zh** [comment]
I approve this motion to relicense DPsim under the MPL2.

**Comment by n-eiling** [comment]
I approve this motion to relicense DPsim under the MPL2.

**Comment by fwege** [comment]
I approve this motion to relicense DPsim under the MPL2

**Comment by dinkelbachjan** [comment]
I approve this motion to relicense DPsim under the MPL2

**Comment by hlubjuhn** [comment]
I approve this motion to relicense DPsim under the MPL2.

**Comment by guelfey** [comment]
I approve this motion to relicense DPsim under the MPL2.

**Comment by VivianeSaGu** [comment]
I approve this motion to relicense DPsim under the MPL2.

**Comment by m-mirz** [comment]
Thank you for approving this. Then, I close this issue :-)
